export const defaultSelectedCountries = [
  'CN',
  'CY',
  'DE',
  'EE',
  'ES',
  'FR',
  'GB',
  'IL',
  'IS',
  'IT',
  'KZ',
  'LT',
  'LV',
  'MC',
  'MD',
  'MO',
  'NO',
  'RU',
  'SE',
  'TR',
  'UA',
];
export const countryCodes = [
  { isoCode: 'AD', name: 'Andorra', fifaCode: 'AND' },
  { isoCode: 'AE', name: 'United Arab Emirates', fifaCode: 'UAE' },
  { isoCode: 'AF', name: 'Afghanistan', fifaCode: 'AFG' },
  { isoCode: 'AG', name: 'Antigua and Barbuda', fifaCode: 'ATG' },
  { isoCode: 'AI', name: 'Anguilla', fifaCode: 'AIA' },
  { isoCode: 'AL', name: 'Albania', fifaCode: 'ALB' },
  { isoCode: 'AM', name: 'Armenia', fifaCode: 'ARM' },
  { isoCode: 'AO', name: 'Angola', fifaCode: 'ANG' },
  { isoCode: 'AQ', name: 'Antarctica', fifaCode: 'ATA' },
  { isoCode: 'AR', name: 'Argentina', fifaCode: 'ARG' },
  { isoCode: 'AS', name: 'American Samoa', fifaCode: 'ASA' },
  { isoCode: 'AT', name: 'Austria', fifaCode: 'AUT' },
  { isoCode: 'AU', name: 'Australia', fifaCode: 'AUS' },
  { isoCode: 'AW', name: 'Aruba', fifaCode: 'ARU' },
  { isoCode: 'AZ', name: 'Azerbaijan', fifaCode: 'AZE' },
  { isoCode: 'BA', name: 'Bosnia and Herzegovina', fifaCode: 'BIH' },
  { isoCode: 'BB', name: 'Barbados', fifaCode: 'BRB' },
  { isoCode: 'BD', name: 'Bangladesh', fifaCode: 'BAN' },
  { isoCode: 'BE', name: 'Belgium', fifaCode: 'BEL' },
  { isoCode: 'BF', name: 'Burkina Faso', fifaCode: 'BFA' },
  { isoCode: 'BG', name: 'Bulgaria', fifaCode: 'BUL' },
  { isoCode: 'BH', name: 'Bahrain', fifaCode: 'BHR' },
  { isoCode: 'BI', name: 'Burundi', fifaCode: 'BDI' },
  { isoCode: 'BJ', name: 'Benin', fifaCode: 'BEN' },
  { isoCode: 'BL', name: 'Saint Barthelemy', fifaCode: 'BLM' },
  { isoCode: 'BM', name: 'Bermuda', fifaCode: 'BER' },
  { isoCode: 'BN', name: 'Brunei Darussalam', fifaCode: 'BRU' },
  { isoCode: 'BO', name: 'Bolivia', fifaCode: 'BOL' },
  { isoCode: 'BQ', name: 'Bonaire, Saint Eustatius and Saba', fifaCode: 'BES' },
  { isoCode: 'BR', name: 'Brazil', fifaCode: 'BRA' },
  { isoCode: 'BS', name: 'Bahamas', fifaCode: 'BAH' },
  { isoCode: 'BT', name: 'Bhutan', fifaCode: 'BHU' },
  { isoCode: 'BV', name: 'Bouvet Island', fifaCode: 'BVT' },
  { isoCode: 'BW', name: 'Botswana', fifaCode: 'BOT' },
  { isoCode: 'BY', name: 'Belarus', fifaCode: 'BLR' },
  { isoCode: 'BZ', name: 'Belize', fifaCode: 'BLZ' },
  { isoCode: 'CA', name: 'Canada', fifaCode: 'CAN' },
  { isoCode: 'CC', name: 'Cocos (Keeling) Islands', fifaCode: 'CCK' },
  { isoCode: 'CD', name: 'Congo, Democratic Republic of the', fifaCode: 'COD' },
  { isoCode: 'CF', name: 'Central African Republic', fifaCode: 'CTA' },
  { isoCode: 'CG', name: 'Congo', fifaCode: 'CGO' },
  { isoCode: 'CH', name: 'Switzerland', fifaCode: 'SUI' },
  { isoCode: 'CI', name: "Cote d'Ivoire", fifaCode: 'CIV' },
  { isoCode: 'CK', name: 'Cook Islands', fifaCode: 'COK' },
  { isoCode: 'CL', name: 'Chile', fifaCode: 'CHI' },
  { isoCode: 'CM', name: 'Cameroon', fifaCode: 'CMR' },
  { isoCode: 'CN', name: 'China', fifaCode: 'CHN' },
  { isoCode: 'CO', name: 'Colombia', fifaCode: 'COL' },
  { isoCode: 'CR', name: 'Costa Rica', fifaCode: 'CRC' },
  { isoCode: 'CU', name: 'Cuba', fifaCode: 'CUB' },
  { isoCode: 'CV', name: 'Cape Verde', fifaCode: 'CPV' },
  { isoCode: 'CW', name: 'Curacao', fifaCode: 'CUW' },
  { isoCode: 'CX', name: 'Christmas Island', fifaCode: 'CXR' },
  { isoCode: 'CY', name: 'Cyprus', fifaCode: 'CYP' },
  { isoCode: 'CZ', name: 'Czech Republic', fifaCode: 'CZE' },
  { isoCode: 'DE', name: 'Germany', fifaCode: 'GER' },
  { isoCode: 'DJ', name: 'Djibouti', fifaCode: 'DJI' },
  { isoCode: 'DK', name: 'Denmark', fifaCode: 'DEN' },
  { isoCode: 'DM', name: 'Dominica', fifaCode: 'DMA' },
  { isoCode: 'DO', name: 'Dominican Republic', fifaCode: 'DOM' },
  { isoCode: 'DZ', name: 'Algeria', fifaCode: 'ALG' },
  { isoCode: 'EC', name: 'Ecuador', fifaCode: 'ECU' },
  { isoCode: 'EE', name: 'Estonia', fifaCode: 'EST' },
  { isoCode: 'EG', name: 'Egypt', fifaCode: 'EGY' },
  { isoCode: 'EH', name: 'Western Sahara', fifaCode: 'ESH' },
  { isoCode: 'ER', name: 'Eritrea', fifaCode: 'ERI' },
  { isoCode: 'ES', name: 'Spain', fifaCode: 'ESP' },
  { isoCode: 'ET', name: 'Ethiopia', fifaCode: 'ETH' },
  { isoCode: 'FI', name: 'Finland', fifaCode: 'FIN' },
  { isoCode: 'FJ', name: 'Fiji', fifaCode: 'FIJ' },
  { isoCode: 'FK', name: 'Falkland Islands (Malvinas)', fifaCode: 'FLK' },
  { isoCode: 'FM', name: 'Micronesia, Federated States of', fifaCode: 'FSM' },
  { isoCode: 'FO', name: 'Faroe Islands', fifaCode: 'FRO' },
  { isoCode: 'FR', name: 'France', fifaCode: 'FRA' },
  { isoCode: 'GA', name: 'Gabon', fifaCode: 'GAB' },
  { isoCode: 'GB', name: 'United Kingdom', fifaCode: 'GBR' },
  { isoCode: 'GD', name: 'Grenada', fifaCode: 'GRN' },
  { isoCode: 'GE', name: 'Georgia', fifaCode: 'GEO' },
  { isoCode: 'GF', name: 'French Guiana', fifaCode: 'GUF' },
  { isoCode: 'GH', name: 'Ghana', fifaCode: 'GHA' },
  { isoCode: 'GI', name: 'Gibraltar', fifaCode: 'GIB' },
  { isoCode: 'GG', name: 'Guernsey', fifaCode: 'GGY' },
  { isoCode: 'GL', name: 'Greenland', fifaCode: 'GRL' },
  { isoCode: 'GM', name: 'Gambia', fifaCode: 'GAM' },
  { isoCode: 'GN', name: 'Guinea', fifaCode: 'GUI' },
  { isoCode: 'GP', name: 'Guadeloupe', fifaCode: 'GLP' },
  { isoCode: 'GQ', name: 'Equatorial Guinea', fifaCode: 'EQG' },
  { isoCode: 'GR', name: 'Greece', fifaCode: 'GRE' },
  { isoCode: 'GS', name: 'South Georgia/South Sandwich Isl.', fifaCode: 'SGS' },
  { isoCode: 'GT', name: 'Guatemala', fifaCode: 'GUA' },
  { isoCode: 'GU', name: 'Guam', fifaCode: 'GUM' },
  { isoCode: 'GW', name: 'Guinea-Bissau', fifaCode: 'GNB' },
  { isoCode: 'GY', name: 'Guyana', fifaCode: 'GUY' },
  { isoCode: 'HK', name: 'Hong Kong', fifaCode: 'HKG' },
  { isoCode: 'HM', name: 'Heard Island and Mcdonald Islands', fifaCode: 'HMD' },
  { isoCode: 'HN', name: 'Honduras', fifaCode: 'HUN' },
  { isoCode: 'HR', name: 'Croatia', fifaCode: 'CRO' },
  { isoCode: 'HT', name: 'Haiti', fifaCode: 'HAI' },
  { isoCode: 'HU', name: 'Hungary', fifaCode: 'HUN' },
  { isoCode: 'ID', name: 'Indonesia', fifaCode: 'IDN' },
  { isoCode: 'IE', name: 'Ireland', fifaCode: 'IRL' },
  { isoCode: 'IL', name: 'Israel', fifaCode: 'ISR' },
  { isoCode: 'IM', name: 'Isle of Man', fifaCode: 'IMN' },
  { isoCode: 'IN', name: 'India', fifaCode: 'IND' },
  { isoCode: 'IO', name: 'British Indian Ocean Territory', fifaCode: 'IOT' },
  { isoCode: 'IQ', name: 'Iraq', fifaCode: 'IRQ' },
  { isoCode: 'IR', name: 'Iran', fifaCode: 'IRN' },
  { isoCode: 'IS', name: 'Iceland', fifaCode: 'ISL' },
  { isoCode: 'IT', name: 'Italy', fifaCode: 'ITA' },
  { isoCode: 'JE', name: 'Jersey', fifaCode: 'JEY' },
  { isoCode: 'JM', name: 'Jamaica', fifaCode: 'JAM' },
  { isoCode: 'JO', name: 'Jordan', fifaCode: 'JOR' },
  { isoCode: 'JP', name: 'Japan', fifaCode: 'JPN' },
  { isoCode: 'KE', name: 'Kenya', fifaCode: 'KEN' },
  { isoCode: 'KG', name: 'Kyrgyzstan', fifaCode: 'KGZ' },
  { isoCode: 'KH', name: 'Cambodia', fifaCode: 'CAM' },
  { isoCode: 'KI', name: 'Kiribati', fifaCode: 'KIR' },
  { isoCode: 'KM', name: 'Comoros', fifaCode: 'COM' },
  { isoCode: 'KN', name: 'Saint Kitts and Nevis', fifaCode: 'SKN' },
  { isoCode: 'KP', name: 'North Korea', fifaCode: 'PRK' },
  { isoCode: 'KR', name: 'South Korea', fifaCode: 'KOR' },
  { isoCode: 'KW', name: 'Kuwait', fifaCode: 'KUW' },
  { isoCode: 'KY', name: 'Cayman Islands', fifaCode: 'CAY' },
  { isoCode: 'KZ', name: 'Kazakhstan', fifaCode: 'KAZ' },
  { isoCode: 'LA', name: 'Laos', fifaCode: 'LAO' },
  { isoCode: 'LB', name: 'Lebanon', fifaCode: 'LIB' },
  { isoCode: 'LC', name: 'Saint Lucia', fifaCode: 'LCA' },
  { isoCode: 'LI', name: 'Liechtenstein', fifaCode: 'LIE' },
  { isoCode: 'LK', name: 'Sri Lanka', fifaCode: 'SRI' },
  { isoCode: 'LR', name: 'Liberia', fifaCode: 'LBR' },
  { isoCode: 'LS', name: 'Lesotho', fifaCode: 'LES' },
  { isoCode: 'LT', name: 'Lithuania', fifaCode: 'LTU' },
  { isoCode: 'LU', name: 'Luxembourg', fifaCode: 'LUX' },
  { isoCode: 'LV', name: 'Latvia', fifaCode: 'LVA' },
  { isoCode: 'LY', name: 'Libyan Arab Jamahiriya', fifaCode: 'LBY' },
  { isoCode: 'MA', name: 'Morocco', fifaCode: 'MAR' },
  { isoCode: 'MC', name: 'Monaco', fifaCode: 'MCO' },
  { isoCode: 'MD', name: 'Moldova', fifaCode: 'MDA' },
  { isoCode: 'ME', name: 'Montenegro', fifaCode: 'MNE' },
  { isoCode: 'MG', name: 'Madagascar', fifaCode: 'MAD' },
  { isoCode: 'MH', name: 'Marshall Islands', fifaCode: 'MHL' },
  { isoCode: 'MK', name: 'Macedonia', fifaCode: 'MKD' },
  { isoCode: 'ML', name: 'Mali', fifaCode: 'MLI' },
  { isoCode: 'MM', name: 'Myanmar', fifaCode: 'MYA' },
  { isoCode: 'MN', name: 'Mongolia', fifaCode: 'MGL' },
  { isoCode: 'MO', name: 'Macau', fifaCode: 'MAC' },
  { isoCode: 'MP', name: 'Northern Mariana Islands', fifaCode: 'MNP' },
  { isoCode: 'MQ', name: 'Martinique', fifaCode: 'MTQ' },
  { isoCode: 'MR', name: 'Mauritania', fifaCode: 'MTN' },
  { isoCode: 'MS', name: 'Montserrat', fifaCode: 'MSR' },
  { isoCode: 'MT', name: 'Malta', fifaCode: 'MLT' },
  { isoCode: 'MU', name: 'Mauritius', fifaCode: 'MRI' },
  { isoCode: 'MV', name: 'Maldives', fifaCode: 'MDV' },
  { isoCode: 'MW', name: 'Malawi', fifaCode: 'MWI' },
  { isoCode: 'MX', name: 'Mexico', fifaCode: 'MEX' },
  { isoCode: 'MY', name: 'Malaysia', fifaCode: 'MAS' },
  { isoCode: 'MZ', name: 'Mozambique', fifaCode: 'MOZ' },
  { isoCode: 'NA', name: 'Namibia', fifaCode: 'NAM' },
  { isoCode: 'NC', name: 'New Caledonia', fifaCode: 'NCL' },
  { isoCode: 'NE', name: 'Niger', fifaCode: 'NIG' },
  { isoCode: 'NF', name: 'Norfolk Island', fifaCode: 'NFK' },
  { isoCode: 'NG', name: 'Nigeria', fifaCode: 'NGA' },
  { isoCode: 'NI', name: 'Nicaragua', fifaCode: 'NCA' },
  { isoCode: 'NL', name: 'Netherlands', fifaCode: 'NED' },
  { isoCode: 'NO', name: 'Norway', fifaCode: 'NOR' },
  { isoCode: 'NP', name: 'Nepal', fifaCode: 'NEP' },
  { isoCode: 'NR', name: 'Nauru', fifaCode: 'NIR' },
  { isoCode: 'NU', name: 'Niue', fifaCode: 'NIU' },
  { isoCode: 'NZ', name: 'New Zealand', fifaCode: 'NZL' },
  { isoCode: 'OM', name: 'Oman', fifaCode: 'OMA' },
  { isoCode: 'PA', name: 'Panama', fifaCode: 'PAN' },
  { isoCode: 'PE', name: 'Peru', fifaCode: 'PER' },
  { isoCode: 'PF', name: 'French Polynesia', fifaCode: 'PYF' },
  { isoCode: 'PG', name: 'Papua New Guinea', fifaCode: 'PNG' },
  { isoCode: 'PH', name: 'Philippines', fifaCode: 'PHI' },
  { isoCode: 'PK', name: 'Pakistan', fifaCode: 'PAK' },
  { isoCode: 'PL', name: 'Poland', fifaCode: 'POL' },
  { isoCode: 'PM', name: 'Saint Pierre and Miquelon', fifaCode: 'SPM' },
  { isoCode: 'PN', name: 'Pitcairn', fifaCode: 'SPM' },
  { isoCode: 'PR', name: 'Puerto Rico', fifaCode: 'PUR' },
  { isoCode: 'PS', name: 'Palestinian Territory, Occupied', fifaCode: 'PLE' },
  { isoCode: 'PT', name: 'Portugal', fifaCode: 'POR' },
  { isoCode: 'PW', name: 'Palau', fifaCode: 'PLW' },
  { isoCode: 'PY', name: 'Paraguay', fifaCode: 'PAR' },
  { isoCode: 'QA', name: 'Qatar', fifaCode: 'QAT' },
  { isoCode: 'RE', name: 'Reunion', fifaCode: 'REU' },
  { isoCode: 'RO', name: 'Romania', fifaCode: 'ROU' },
  { isoCode: 'RS', name: 'Serbia', fifaCode: 'SRB' },
  { isoCode: 'RU', name: 'Russian Federation', fifaCode: 'RUS' },
  { isoCode: 'RW', name: 'Rwanda', fifaCode: 'RWA' },
  { isoCode: 'SA', name: 'Saudi Arabia', fifaCode: 'KSA' },
  { isoCode: 'SB', name: 'Solomon Islands', fifaCode: 'SOL' },
  { isoCode: 'SC', name: 'Seychelles', fifaCode: 'SEY' },
  { isoCode: 'SD', name: 'Sudan', fifaCode: 'SUD' },
  { isoCode: 'SE', name: 'Sweden', fifaCode: 'SWE' },
  { isoCode: 'SG', name: 'Singapore', fifaCode: 'SIN' },
  { isoCode: 'SH', name: 'Saint Helena', fifaCode: 'SHN' },
  { isoCode: 'SI', name: 'Slovenia', fifaCode: 'SVN' },
  { isoCode: 'SJ', name: 'Svalbard and Jan Mayen', fifaCode: 'SJM' },
  { isoCode: 'SK', name: 'Slovakia', fifaCode: 'SVK' },
  { isoCode: 'SL', name: 'Sierra Leone', fifaCode: 'SLE' },
  { isoCode: 'SM', name: 'San Marino', fifaCode: 'SMR' },
  { isoCode: 'SN', name: 'Senegal', fifaCode: 'SEN' },
  { isoCode: 'SO', name: 'Somalia', fifaCode: 'SOM' },
  { isoCode: 'SR', name: 'Suriname', fifaCode: 'SUR' },
  { isoCode: 'SS', name: 'South Sudan', fifaCode: 'SCO' },
  { isoCode: 'ST', name: 'Sao Tome and Principe', fifaCode: 'STP' },
  { isoCode: 'SV', name: 'El Salvador', fifaCode: 'SLV' },
  { isoCode: 'SX', name: 'Sint Maarten', fifaCode: 'SXM' },
  { isoCode: 'SY', name: 'Syrian Arab Republic', fifaCode: 'SYR' },
  { isoCode: 'SZ', name: 'Swaziland', fifaCode: 'SWZ' },
  { isoCode: 'TC', name: 'Turks and Caicos Islands', fifaCode: 'TCA' },
  { isoCode: 'TD', name: 'Chad', fifaCode: 'CHA' },
  { isoCode: 'TF', name: 'French Southern Territories', fifaCode: 'ATF' },
  { isoCode: 'TG', name: 'Togo', fifaCode: 'TGO' },
  { isoCode: 'TH', name: 'Thailand', fifaCode: 'THA' },
  { isoCode: 'TJ', name: 'Tajikistan', fifaCode: 'TJK' },
  { isoCode: 'TK', name: 'Tokelau', fifaCode: 'TKL' },
  { isoCode: 'TM', name: 'Turkmenistan', fifaCode: 'TKM' },
  { isoCode: 'TN', name: 'Tunisia', fifaCode: 'TUN' },
  { isoCode: 'TO', name: 'Tonga', fifaCode: 'TGA' },
  { isoCode: 'TL', name: 'East Timor', fifaCode: 'TLS' },
  { isoCode: 'TR', name: 'Turkey', fifaCode: 'TUR' },
  { isoCode: 'TT', name: 'Trinidad and Tobago', fifaCode: 'TRI' },
  { isoCode: 'TV', name: 'Tuvalu', fifaCode: 'TUV' },
  { isoCode: 'TW', name: 'Taiwan, Province of China', fifaCode: 'TPE' },
  { isoCode: 'TZ', name: 'Tanzania, United Republic of', fifaCode: 'TAN' },
  { isoCode: 'UA', name: 'Ukraine', fifaCode: 'UKR' },
  { isoCode: 'UG', name: 'Uganda', fifaCode: 'UGA' },
  { isoCode: 'UM', name: 'USA Minor Outlying Islands', fifaCode: 'UMI' },
  { isoCode: 'US', name: 'United States', fifaCode: 'USA' },
  { isoCode: 'UY', name: 'Uruguay', fifaCode: 'URU' },
  { isoCode: 'UZ', name: 'Uzbekistan', fifaCode: 'UZB' },
  { isoCode: 'VA', name: 'Vatican City State', fifaCode: 'VAT' },
  { isoCode: 'VC', name: 'St Vincent and the Grenadines', fifaCode: 'VIN' },
  { isoCode: 'VE', name: 'Venezuela', fifaCode: 'VEN' },
  { isoCode: 'VG', name: 'Virgin Islands, British', fifaCode: 'VGB' },
  { isoCode: 'VI', name: 'Virgin Islands, U.S.', fifaCode: 'VIR' },
  { isoCode: 'VN', name: 'Viet Nam', fifaCode: 'VIE' },
  { isoCode: 'VU', name: 'Vanuatu', fifaCode: 'VAN' },
  { isoCode: 'WF', name: 'Wallis and Futuna', fifaCode: 'WLF' },
  { isoCode: 'WS', name: 'Samoa', fifaCode: 'SAM' },
  { isoCode: 'YE', name: 'Yemen', fifaCode: 'YEM' },
  { isoCode: 'YT', name: 'Mayotte', fifaCode: 'MYT' },
  { isoCode: 'ZA', name: 'South Africa', fifaCode: 'RSA' },
  { isoCode: 'ZM', name: 'Zambia', fifaCode: 'ZAM' },
  { isoCode: 'ZW', name: 'Zimbabwe', fifaCode: 'ZIM' },
];
